import { writeFileSync } from 'node:fs';
import { tokens } from '@abfahrt/tokens';

const { colors, spacing, typography, layout, shape } = tokens;
const px = (n: number) => `${n}px`;

const lines = [
  '  /* colors */',
  `  --color-chrome: ${colors.chrome};`,
  `  --color-chalk: ${colors.chalk};`,
  `  --color-rule: ${colors.rule};`,
  `  --color-ink: ${colors.ink};`,
  `  --color-platform: ${colors.platform};`,
  `  --color-signal: ${colors.signal};`,
  '',
  '  /* spacing */',
  `  --space-xs: ${px(spacing.xs)};`,
  `  --space-sm: ${px(spacing.sm)};`,
  `  --space-md: ${px(spacing.md)};`,
  `  --space-lg: ${px(spacing.lg)};`,
  `  --space-xl: ${px(spacing.xl)};`,
  `  --space-xxl: ${px(spacing.xxl)};`,
  `  --space-baseline: ${px(spacing.baseline)};`,
  '',
  '  /* typography */',
  `  --font-standard: ${typography.families.standard};`,
  `  --font-narrow: ${typography.families.narrow};`,
  `  --text-label: ${px(typography.sizes.label)};`,
  `  --text-row: ${px(typography.sizes.row)};`,
  `  --text-body: ${px(typography.sizes.body)};`,
  `  --text-display: ${px(typography.sizes.display)};`,
  `  --weight-regular: ${typography.weights.regular};`,
  `  --weight-medium: ${typography.weights.medium};`,
  `  --weight-semibold: ${typography.weights.semibold};`,
  `  --weight-bold: ${typography.weights.bold};`,
  `  --tracking-board-header: ${typography.tracking.boardHeader}em;`,
  `  --tracking-panel-header: ${typography.tracking.panelHeader}em;`,
  `  --font-width-expanded: ${typography.widths.expanded}%;`,
  '',
  '  /* layout */',
  `  --layout-columns: ${layout.columns};`,
  `  --layout-gutter: ${px(layout.gutter)};`,
  `  --board-row-height: ${px(layout.boardRowHeight)};`,
  '',
  '  /* shape */',
  `  --radius: ${px(shape.radius)};`,
  `  --hairline: ${px(shape.hairline)};`,
  `  --signal-bar: ${px(shape.signalBar)};`,
];

const css = `/* generated by scripts/generate-token-css.ts — do not edit */\n:root {\n${lines.join('\n')}\n}\n`;

writeFileSync('src/generated/tokens.css', css);
